# Generated by Django 3.2.25 on 2024-07-19 12:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tasks.mixins


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0047_merge_20240318_2210'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewerAnnotationLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Creation time', verbose_name='created at')),
                ('annotation', models.ForeignKey(help_text='Corresponding annotation for this reviewer annotation', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviewer_annotations', to='tasks.annotation')),
                ('reviewer', models.ForeignKey(help_text='User who created this reviewer annotation', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviewer_annotations', to=settings.AUTH_USER_MODEL)),
            ],
            bases=(tasks.mixins.AnnotationMixin, models.Model),
        ),
    ]
