# Generated by Django 3.2.25 on 2024-09-16 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0026_auto_20231103_0020'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmember',
            name='user_role',
            field=models.CharField(choices=[('OWNER', 'OWNER'), ('ADMINISTRATOR', 'ADMINISTRATOR'), ('MANAGER', 'MANAGER'), ('REVIEWER', 'REVIEWER'), ('ANNOTATOR', 'ANNOTATOR')], default='ANNOTATOR', max_length=20),
        ),
    ]
