# Generated by Django 3.2.25 on 2024-07-06 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20231201_0001'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('OWNER', 'OWNER'), ('ADMINISTRATOR', 'ADMINISTRATOR'), ('MANAGER', 'MANAGER'), ('REVIEWER', 'REVIEWER'), ('ANNOTATOR', 'ANNOTATOR')], default='ANNOTATOR', max_length=20),
        ),
    ]
